fastify/fastify-rate-limit

- store/LocalStore.js
Fixes #13 (now reverted), #15 
see: https://github.com/avoidwork/tiny-lru/commit/d0cdcfefdc740bf2ec5c544de8d7971e0ab4cb31
> Use public clear function instead of reset

- README.md
Fix #27 
Change req.ip to req.raw.ip in docs for keyGenerator function.
> req.ip to req.raw.ip change in docs

- index.d.ts
- package.json
- types.test.ts
Since we have a dependency to `ioredis` and not `redis` we should
also use the corresponding `@types`.
> Replace @types/redis with @types/ioredis

- package.json
the package.json is not update.
the v2.3.0 is [published in npm](https://www.npmjs.com/package/fastify-rate-limit/v/2.3.0) already
the [release in GH is ok](https://github.com/fastify/fastify-rate-limit/releases/tag/v2.3.0)
so I think a `git push` (from releasify) has failed
> fix: package version

- index.js
- store/LocalStore.js
- store/RedisStore.js
- test/route-rate-limit.test.js
Adding #61 I found this bug that will create a `setInterval` with a time of `undefined` if the user doesn't set the `timeWindow` param in route's configuration.
The current 2.4.0 version is affected
> Fix time window undefined

- index.js
- test/global-rate-limit.test.js
- test/route-rate-limit.test.js
Move to the onRequest hook earlier in the lifecycle and adds tests to confirm nothing further is called int he lifecycle when rate limit is exceeded. 
Fixes #83
> move to onRequest hook

- README.md
- index.js
( firstly thank you the fastify eco system )
Update the plugin version from 2.x to a semver range of 2.x - 3.x. The dependency in package.json indicates fastify version 3. On updating fastify version to a range for the plugin and carrying out integration testing using autocannon to test the change the plugin was found to behave as expected. The package was built locally and published locally via verdaccio.
This was tested locally on node versions
- 10.10.0
- 12.3.1
- 14.1.0
By making a contribution to this project, I certify that:
* (a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
* (b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an …
> Feature/fastify-rate-limit add semver range to the plugin 

- index.d.ts
This is a very simple fix. `timeWindow` accepts a `string` or `number` (see https://github.com/fastify/fastify-rate-limit/blob/master/index.js#L39), but, in the typescript declaration, only accepts `number`. This PR adds `string` type in the declaration file
> fix: timeWindow type can be number or string

- README.md
- index.js
- package.json
- test/global-rate-limit.test.js
- test/route-rate-limit.test.js
Fix #121 
Just a question in the code since it seems to me that a piece of code is no more necessary since the `Error` is managed internally by fastify (for this reason the `application/json` string has changed)
> fix error handler call

- index.js
- test/route-rate-limit.test.js
> do not set onRequest twice

- README.md
- index.d.ts
- index.js
- test/global-rate-limit.test.js
- test/route-rate-limit.test.js
#108 
This PR integrates the IETF standard rate-limit format. You can see the  latest version of the document at [draft-ietf-httpapi-ratelimit-headers.md](https://github.com/ietf-wg-httpapi/ratelimit-headers/blob/f6a7bc7560a776ea96d800cf5ed3752d6d397b06/draft-ietf-httpapi-ratelimit-headers.md).
Considering it's still a draft version, it's possible to activate it optionally using the `enableDraftSpec` parameter. 
List of header which may change:
````
x-ratelimit-limit -> ratelimit-limit
x-ratelimit-remaining -> ratelimit-remaining
x-ratelimit-reset -> ratelimit-reset
````
The documentation uses CamelCase format but fastify only supports LowerCase.
> fea(#108): Modified rate limit headers following IETF standard.

- index.js
- test/route-rate-limit.test.js
Closes #129 
Fixes regression of PR #123 (v5.0.1) by moving symbol inside function scope to be able to register multiple rate limiters again.
> fix: registration of multiple rate limiter

- index.js
- package.json
- test/route-rate-limit.test.js
In https://github.com/fastify/fastify-rate-limit/pull/126, we added the support for using async functions for `max`.
However this left a mixture of promises and callbacks that could cause havoc and made the code harder to understand.
Bonus point: I've found a bug and fixed it.
> Rewrite to async to avoid mixing async and callbacks

- README.md
- index.d.ts
- index.js
- test/not-found-handler-rate-limited.js
- test/types/types.test.ts
Addresses #127
This adds the ability for users to rate limit the setNotFoundHandler.
An attacker could search for valid URLs if your 404 error handling is not rate limited.
- [ x] run `npm run test` ~and `npm run benchmark`~ (comment: `benchmark` script does not exist)
- [ x] tests and/or benchmarks are included
- [ x] documentation is changed or added
- [ x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
> Add ability to rate limit 404 handler

- package.json
-----
I've done this for the following reasons:
1. The GitHub CI use the latest tag for Redis so I'm syncing the versions so no weird problem occurs when the local machine and the CI uses 2 different versions (I think it's best to pin to a specific version)
2. The current version doesn't have an ARM image which is a problem with the rise of the M1 CPUs (which is how I notice the problem)
> chore: remove specific version from initiating redis for local tests

- test/global-rate-limit.test.js
----
I'll clean the rest of the tests, just wanted to know if it's a desirable change, no logic has been changed
For easier review, I advise you to check the _Hide whitespace_ checkbox
> Clean tests

- test/global-rate-limit.test.js
According to the docs in [IETF Draft Spec Headers](https://github.com/fastify/fastify-rate-limit#ietf-draft-spec-headers), when `enableDraftSpec` is `true` then:
> `ratelimit-reset`: how many seconds must pass before the rate limit resets
> `retry-after`: contains the **same value in time as `ratelimit-reset`**
and the test checked that the `ratelimit-remaining` header is equal to `retry-after`
> test: fix 'enabled-IETF-draft-spec' test

- index.d.ts
- package.json
- test/types/types.test.ts
Hello.
This PR aims to:
- upgrade package dependencies
- update typescript definitions
- fix typescript tests by using `import { default as ioredis } from 'ioredis'` syntax to import ioredis (following https://github.com/fastify/fastify-rate-limit/pull/198 CI typescript test failure)
> fix (types): fix typescript tests and update typescript definitions

- index.js
- package.json
- store/LocalStore.js
- test/github-issues/issue-207.test.js
also changed the package.json so tap would run all the tests in the test folder and it's sub directories
fix #207
> Fixing `continueExceeding` option does not reset rate-limit - #207

- README.md
- index.d.ts
- index.js
- test/global-rate-limit.test.js
- test/route-rate-limit.test.js
- test/types/types.test.ts
onExceeding and onExceeded to be available
issue #232 
> fix: added onExceeding and onExceeded to be available

- README.md
- index.d.ts
- index.js
- test/global-rate-limit.test.js
- test/types/types.test.ts
> add the "key" in the "onExceeding" and "onBanReach"

- test/global-rate-limit.test.js
- test/route-rate-limit.test.js
We were running the unit tests in a very flaky way. Instead of actually waiting the redis flushall command we were having a noop callback. So it could happen, that flushall was not done and we were already running the next test.
This PR fixes that by implementing a teardown for those redis tests and fixing the corresponding assertions. 
> test: fix flaky redis unit tests

- index.js
- package.json
- test/route-rate-limit.test.js
There was a bug in fastify core, where an onRoute hook would be called twice on automatic generated HEAD routes. This was fixed in core. This PR fixes unit tests and adds one regarding the expected behaviour.
> tests: head routes get applied rate limiting hook only once

- README.md
- index.js
- test/github-issues/issue-284.test.js
- test/route-rate-limit.test.js
> Don't set the reply code automatically

- index.js
- test/global-rate-limit.test.js
- test/not-found-handler-rate-limited.test.js
- test/route-rate-limit.test.js
> fix: retry-after should be in seconds when specified timeWindow

- index.js
All custom function parameters, like `onExceeded` and `onExceeding`, only get run if they're defined. However, `onBan` has a default function that is just empty (old, line 281, 268)
Under stress from an IP, that function can get called thousands of times, which probably still wouldn't cause a problem (🤣), but why run it in the first place?
> chore: remove defaultOnBanReach helper fn

- index.js
- test/global-rate-limit.test.js
- test/not-found-handler-rate-limited.test.js
- test/route-rate-limit.test.js
`Retry-After`, the internet standard counterpart of `x-ratelimit-reset`, was for some reason always being set to the `timeWindow` property when rate limiting took place - so for instance even when a user had to wait for 5 more seconds for rate limiting to be lifted (with a timeWindow of 15 seconds), the user would still see on the header the number 15 instead of 5
[I traced back a change](https://github.com/fastify/fastify-rate-limit/commit/6de4257297e7bb23d6fc4d0e1eeefa36d3b987a5#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R188) that, while introducing the optional draft headers feature, had done away with this but probably couldn't change the default behavior to make it non-breaking
[While another breaking PR is …
> Retry-After: return the TTL instead of timeWindow

- index.js
- test/global-rate-limit.test.js
- test/not-found-handler-rate-limited.test.js
- test/route-rate-limit.test.js
Last (small) breaking change, promise 😁
Here's the case for it: it changes nothing on our side, but sending an endpoint `Retry-After: 0` is arguably worse than sending `Retry-After: 1` when they still have 900ms of blockage
Also, the whole idea of sending `Retry-After: 0` makes no sense
And finally, all tests that contained checks against multiple values have been modified
> Use `Math.ceil` for timeLeft calculation

- index.js
- store/RedisStore.js
- test/global-rate-limit.test.js
- test/route-rate-limit.test.js
Here's what it fixes concretely:
- When a route's parent's `allowList` is a function and the child's isn't, the app will crash because the code makes a weird check to see if the *parent*'s parameter is a function and if so, calls `params.allowList` as a function (!), the params config's `allowList` can also be an array of IPs though (coming from the config object) and crash the app upon invocation
https://github.com/fastify/fastify-rate-limit/blob/18df4d3a33d32bf9c71f2d842117140e7e3b4bfc/index.js#L190-L198
- The rateLimit decorator also ignores the configuration when the `timeWindow` property isn't set. However, there might be times where we only want to change the max, or some other parameter
https://github.com/fastify/fastify-rate-limit/blob/18df4d3a33d32bf9c71f2d842117140e7e3b4bfc/index …
> Refactor `index.js` to fix multiple bugs
