fastify/fastify-rate-limit

- .gitattributes
- README.md
- index.js
- package.json
> Prepare for 1.x

- index.d.ts
- package.json
- types.test.ts
Fixes issue on importing library in TS project and not installing `@types/ioredis`.
> Removes ioredis as dependency from typings

- package.json
> chore(package): update @types/node to version 12.6.2

- index.js
- test/route-rate-limit.test.js
Most recent release(s) of this plugin breaks my existing Fastify projects that are using per-route configuration (used for another plugin I made)...
I'm submitting this quick fix (and additional test) to solve this issue.
> Fixed issue with existing route config

- README.md
Thanks for your work on this feature! It's much needed. Looking forward to the next release.
> Fix small typo in README with latest dynamic whitelist feature

- README.md
- index.js
- store/LocalStore.js
- store/RedisStore.js
- test/global-rate-limit.test.js
- test/route-rate-limit.test.js
> add ratelimit-reset

- store/LocalStore.js
- test/local-store-close.test.js
Please review, related to (#71). Please add for the next release package. Many thanks.
> fix issue #71 on LocalStore by adding Hook's done callback

- README.md
- example/example-custom.js
- index.js
- store/LocalStore.js
- store/RedisStore.js
- test/route-rate-limit.test.js
> #76 - Added fix to format timewindow on per route config

- index.js
- test/global-rate-limit.test.js
- test/route-rate-limit.test.js
> Do not run the hook twice for HEAD

- README.md
- example/example-knex-mysql.js
Added a working example of Knex.js with MySQL
> Updated docs and added example/example-knex-mysql.js

- index.d.ts
- test/types/types.test.ts
> Change type for max function in RateLimitOptions to support async

- index.js
the function `onIncr` was removed a while ago so updated the comment that left
Sorry for all the little PRs 😬 it's just different things
> chore: remove old invalid implementation comment

- index.js
- package.json
- test/global-rate-limit.test.js
- test/local-store-close.test.js
- test/route-rate-limit.test.js
When checked for number using `typeof <var> === 'number'` then forgot to handle `NaN` which is type `number` but invalid value, currently just handled `NaN` as invalid value but not throwed/warn anything, which is worse IMO so I can change it if needed
> fix: add NaN handling

- index.js
- test/route-rate-limit.test.js
This MR should solve https://github.com/fastify/fastify-rate-limit/issues/178 issue.
> fix: routes allowList

- README.md
> Docs/ Disable specific route

- README.md
- index.d.ts
- index.js
- test/global-rate-limit.test.js
- test/route-rate-limit.test.js
- test/types/types.test.ts
😛 
fixes https://github.com/fastify/fastify-rate-limit/issues/224
> Feat/ Custom hook [#224]

- README.md
- example/example-knex.js
- example/example-sequelize.js
- example/example.js
> chore: replace use of deprecated variadic `listen()`

- README.md
> docs(readme): update supported semver range

- package.json
> build(deps-dev): remove @types/ioredis

- .github/workflows/ci.yml
- .taprc
- package.json
> chore: add lint stage to ci and use pre-commit

- .taprc
- index.js
- test/global-rate-limit.test.js
- test/route-rate-limit.test.js
Well 97% because I have no clue rn to test the error cases of RedisStore. 
> 96% test coverage

- README.md
> chore: compatibility map

- types/index.d.ts
- types/index.test-d.ts
> types: add missing context config

- types/index.d.ts
- types/index.test-d.ts
> types: fix rateLimit:false in route options

- README.md
> doc: typo in Readme
